name: Call Update .gitignore

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight
  workflow_dispatch:

jobs:
  call-update-gitignore:
    uses: andreilgeorgescu/workflow-dependency-gitignore/.github/workflows/update-gitignore.yaml@main
    with:
      url_suffix: 'linux,git,zsh,visualstudiocode,python'
    permissions:
      contents: write
      pull-requests: write
